name: Monte Carlo Pi CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      CC: clang
      CXX: clang++

    steps:
    - name: Setup dependencies
      run: |
        sudo apt-get install -y clang-tidy-10
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-10 100
    - uses: actions/checkout@v1
      with: 
        submodules: recursive
    - name: Prepare build dir
      run: mkdir build
    - name: Generate build files using cmake
      run: cmake .. -DUSE_CLANG_TIDY=TRUE
      working-directory: ./build
    - name: Run make
      run: make
      working-directory: ./build
    - name: Run tests
      timeout-minutes: 5
      run: ./test/runUnitTests
      working-directory: ./build
    - name: Prepare ASAN build dir
      run: mkdir build_asan
    - name: Generate ASAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=ASAN
      working-directory: ./build_asan
    - name: Run ASAN make
      run: make
      working-directory: ./build_asan
    - name: Run ASAN tests
      timeout-minutes: 7
      run: ./test/runUnitTests
      working-directory: ./build_asan
    - name: Prepare USAN build dir
      run: mkdir build_usan
    - name: Generate USAN build files using cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=USAN
      working-directory: ./build_usan
    - name: Run USAN make
      run: make
      working-directory: ./build_usan
    - name: Run USAN tests
      timeout-minutes: 5
      run: ./test/runUnitTests
      working-directory: ./build_usan
